import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const lato = Lato({
  display: "swap",
  weight: ["400", "700", "900", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Omaira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-lato">
      <body className={lato.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
